# This is main hyprland config file.
# For more info go into specific source files.

source = ~/.config/hypr/hyprland/monitors.conf
source = ~/.config/hypr/hyprland/programs.conf
source = ~/.config/hypr/hyprland/autostart.conf
source = ~/.config/hypr/hyprland/envs.conf
source = ~/.config/hypr/hyprland/permissions.conf
source = ~/.config/hypr/hyprland/looks.conf
source = ~/.config/hypr/hyprland/inputs.conf
source = ~/.config/hypr/hyprland/keybindings.conf
source = ~/.config/hypr/hyprland/windows.conf
